# This rule is not used by the project net-chaos-simulator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to net-chaos-simulator.pafev.dev resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: net-chaos-simulator
    app.kubernetes.io/managed-by: kustomize
  name: networkchaos-viewer-role
rules:
- apiGroups:
  - net-chaos-simulator.pafev.dev
  resources:
  - networkchaos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net-chaos-simulator.pafev.dev
  resources:
  - networkchaos/status
  verbs:
  - get
