---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - net-chaos-simulator.pafev.dev
  resources:
  - networkchaos
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - net-chaos-simulator.pafev.dev
  resources:
  - networkchaos/finalizers
  verbs:
  - update
- apiGroups:
  - net-chaos-simulator.pafev.dev
  resources:
  - networkchaos/status
  verbs:
  - get
  - patch
  - update
