apiVersion: net-chaos-simulator.pafev.dev/v1
kind: NetworkChaos
metadata:
  labels:
    app.kubernetes.io/name: net-chaos-simulator
    app.kubernetes.io/managed-by: kustomize
  name: networkchaos-sample
  namespace: default
  finalizers:
    - "net-chaos-simulator.pafev.dev/finalizer"
spec:
  sourceSelector:
    name: ""
    namespace: ""
    labels:
      matchLabels: {}
  targetSelector:
    name: ""
    namespace: ""
    labels:
      matchLabels: {}
  delay: "200ms"
